export enum pathEnum {
  CIRCULAIRE = 'circulaire',
  CLEARCACHE = 'clear-cache',
  SYMBOLE = 'symbole',
  SYMBOLEACCESSORIES = 'symbol-accessories',
  SYMBOLESENS = 'symbol-sens',
  SIGNIFICATION = 'signification',
  FILIERE = 'filiere',
  COLOR = 'color',
  PLACEMENT = 'placement',
  POSITION = 'position',
  //IMG = 'img',
  CIRCULAIRE_COLOR = 'circulaire-color',
  LINK = 'data-link',
  ITEMINDEX = 'item-index',
}
